inherit_from:
  - https://raw.githubusercontent.com/moneyadviceservice/mas-standards/master/.rubocop.yml
Metrics/LineLength:
  Max: 140
Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - uat
    - qa
    - preview
AllCops:
  Exclude:
    - 'Rakefile'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'Guardfile'
    - 'lib/tasks/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/cassettes/**/*'
    - 'features/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'lib/core/*/*/*'
    - 'lib/core/*/*'
    # TODO clean this classes
    - 'app/helpers/application_helper.rb'
    - 'app/controllers/styleguide_controller.rb'
    - 'app/domain/breadcrumb_trail.rb'
    - 'lib/core/repository/categories/fake.rb'
    - 'lib/core/repository/customers/fake.rb'

