FORMAT: 1A
HOST: https://api.moneyadviceservice.org.uk

# Money Advice Service
API for the Money Advice Service's API.

# Group Articles
Article related resources of the **Money Advice Service**

## Articles Collection [/articles]
### List all Articles [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "content": "Jogging in park"
        }, {
          "id": 2, "content": "Pick-up posters from post-office"
        }]

## Article [/articles/{id}]
A single Article object with all its details

+ Parameters
    + slug (required, string, `the-article`) ... String `id` of the Article to perform action with. Has example value.

### Retrieve a Article [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "slug": "the-article", "title": "Pick-up posters from post-office", content: "<p>La de da</p>" }
