FORMAT: 1A
HOST: https://www.moneyadviceservice.org.uk

# Money Advice Service
API for the Money Advice Service, to be consumed by the responsive frontend.

# Group Categories
Category related resources of the **Money Advice Service**.

## Categories Collection [/{locale}/categories.json]
A collection of categories including their subcategories

+ Parameters
    + locale = `en` (optional, string, `en`) ... Locale of the Categories.
        + Values
            + `en`
            + `cy`

### Retrieve all Categories [GET]
+ Response 200 (application/json)

    + Header

            Link: <https://www.moneyadviceservice.org.uk/en/categories; rel="canonical", <https://www.moneyadviceservice.org.uk/cy/categories>; rel="alternate"; hreflang="cy"

    + Body

            [
                {
                    "id": "life-events",
                    "title": "Life events",
                    "description": "When big things happen - having a baby, losing your job, getting divorced or retiring\n - it helps to be in control of your money\n",
                    "subCategories": [
                        {
                            "id": "setting-up-home",
                            "title": "Setting up home",
                            "description": "Deciding whether to rent or buy, working out what you can afford and managing\n money when sharing with others\n",
                            "subCategories": [
                            ]
                        }
                    ]
                }
            ]

## Category [/{locale}/categories/{id}]
A single category object with all its details

+ Parameters
    + locale = `en` (optional, string, `en`) ... Locale of the Category.
        + Values
            + `en`
            + `cy`
    + id (required, string, `life-events`) ... ID of the Category.

### Retrieve a Category [GET]
+ Response 200 (application/json)

    + Header

            Link: <https://www.moneyadviceservice.org.uk/en/categories/life-events>; rel="canonical"; title="Life events", <https://www.moneyadviceservice.org.uk/cy/categories/life-events>; rel="alternate"; hreflang="cy"; title="Digwyddiadau bywyd"

    + Body

            {
                "title": "Life events",
                "description": "When big things happen - having a baby, losing your job, getting divorced or retiring\n - it helps to be in control of your money\n",
                "id":"life-events",
                "contents":[
                  {
                    "id":"setting-up-home",
                    "type":"category",
                    "title":"Setting up home",
                    "description":"Deciding whether to rent or buy, working out what you can afford and managing\n money when sharing with others\n"
                  },
                  {
                    "id":"how-much-rent-can-you-afford",
                    "type":"guide",
                    "title":"How much rent can you afford?",
                    "description":"When working out what rent you can afford, remember to factor in upfront costs and your ongoing bills once you've moved in"
                  }
                ]
            }


# Group Articles
Article related resources of the **Money Advice Service**.

## Article [/{locale}/articles/{id}]
A single Article object with all its details

+ Parameters
    + locale = `en` (optional, string, `en`) ... Locale of the Article.
        + Values
            + `en`
            + `cy`
    + id (required, string, `where-to-go-to-get-free-debt-advice`) ... ID of the Article.

### Retrieve an Article [GET]
+ Response 200 (application/json)

    + Header

            Link: <https://www.moneyadviceservice.org.uk/en/articles/where-to-go-to-get-free-debt-advice>; rel="canonical"; title="Where to go to get free debt advice", <https://www.moneyadviceservice.org.uk/cy/articles/ble-i-gael-cyngor-am-ddim-ynghylch-dyled>; rel="alternate"; hreflang="cy"; title="Ble i gael cyngor am ddim ynghylch dyled"

    + Body

            {
                "title": "Where to go to get free debt advice",
                "description": "Find out where you can get free, confidential help if you are struggling with debt",
                "body": "<h2>Watch out for companies that aren't charities</h2><p>Look out for companies with misleading names that sound like debt charities but are actually commercial businesses.</p><p>Never ever pay for services from this type of company.</p>"
            }

# Group Action Plans
Action Plan related resources of the **Money Advice Service**.

## Action Plan [/{locale}/action_plans/{id}]
A single Action Plan object with all its details

+ Parameters
    + locale = `en` (optional, string, `en`) ... Locale of the Action Plan.
        + Values
            + `en`
            + `cy`

### Retrieve an Action Plan [GET]
+ Response 200 (application/json)

    + Header

            Link: <https://www.moneyadviceservice.org.uk/en/action_plans/prepare-for-the-cost-of-having-a-baby>; rel="canonical"; title="Action plan – Prepare for the cost of having a baby", <https://www.moneyadviceservice.org.uk/cy/action_plans/paratowch-am-y-gost-o-gael-babi>; rel="alternate"; hreflang="cy"; title="Cynllun gweithredu - Paratowch am y gost o gael babi - Gwasanaeth Cynghori Ariannol"

    + Body

            {
                "title": "Prepare for the cost of having a baby",
                "description": "A handy action plan which can help with planning of the costs involved in having a new baby",
                "body": "<h4>Why?</h4><p>Knowing how much everything costs will help you prepare for your new arrival and avoid any unexpected expenses.</p>"
            }
