FORMAT: 1A
HOST: https://api.moneyadviceservice.org.uk

# Money Advice Service
API for the Money Advice Service.

# Articles
Article related resources of the **Money Advice Service**.

## Article [/articles/{id}]
A single Article object with all its details

+ Parameters
    + id (required, string, `foo-bar`) ... String `id` of the Article to perform action with. Has example value.

### Retrieve a Article [GET]
+ Response 200 (application/json)

    + Header

            Link: <https://www.moneyadviceservice.org.uk/cy/articles/ble-i-gael-cyngor-am-ddim-ynghylch-dyled>; rel="alternate"; hreflang="cy"; title="Ble i gael cyngor am ddim ynghylch dyled"

    + Body

            {
                "id": "where-to-go-to-get-free-debt-advice",
                "title": "Where to go to get free debt advice",
                "description": "Find out where you can get free, confidential help if you are struggling with debt"
            }
