#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

export PHANTOMJS_VERSION="2.1.1"
wget "https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2" -O phantomjs.tar.bz2
tar -xvf phantomjs.tar.bz2 phantomjs-2.1.1-linux-x86_64/bin/phantomjs
mv phantomjs-2.1.1-linux-x86_64/bin/phantomjs .
rm -rf phantomjs-2.1.1-linux-x86_64
rm -rf phantomjs.tar.bz2
alias phantomjs=./phantomjs
phantomjs --version
which -a phantomjs
