categories:
  - Debt and borrowing:
    - Before you borrow
    - Taking control of debt
    - Mortgage and rent problems
    - Help with loans
    - Credit cards and credit ratings
  - Budgeting and managing money:
    - Running a bank account
    - Managing your money
    - Student and graduate money
    - Cutting costs
  - Saving and investing:
    - How to save money
    - Types of savings
    - How to invest money
    - Types of investment
  - Work, pensions and retirement:
    - Jobs and tax
    - Redundancy
    - Help with Pensions
    - Types of pension and annuity
    - Workplace pensions
    - Taking income from your pension
    - Managing your money in retirement
  - Benefits:
    - Benefits - what you need to know
    - Child Benefit
    - Universal Credit
    - Benefits at work
  - Births, deaths and family:
    - Having a baby
    - Maternity and paternity rights
    - Making a will
    - When someone dies
    - Divorce and separation
  - Insurance:
    - Help with insurance
    - Home insurance
    - Life and protection Insurance
    - Car insurance
    - Travel insurance
    - Pet insurance
  - Homes and mortgages:
    - Buying a home
    - Help with mortgages
    - Types of mortgage
    - Renting and letting
  - Care and disability:
    - Care advice and help
    - Paying for care
    - Support for carers
    - Disabled people
  - Cars and travel:
    - Finding the right car for you
    - Buying a car
    - Selling a car
    - Running a car
    - Travel money and sending money abroad
