development:
  adapter: mysql2
  username: root
  database: mas_development
  pool: 5
  timeout: 5000
  encoding: utf8

test:
  adapter: mysql2
  host: 127.0.0.1
  username: root
  database: cms_test
  pool: 5
  timeout: 5000
  encoding: utf8
  port: 3306

production:
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  reconnect: true
  url: <%= ENV["DATABASE_URL"] %>
