development:
  adapter: mysql2
  username: root
  database: mas_development
  pool: 5
  timeout: 5000
  encoding: utf8

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  reconnect: true
  url: <%= ENV["MAS_PUBLIC_WEBSITE_DATABASE_URL"] %>
